version: '3.4'

services:
  react:
    build: .
    container_name: nonograms
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9000:9000
    volumes: 
      - .:/usr/src/app
    command: ["npm", "run", "dev"]