name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build container
      run: docker build -t non .
    - name: Run tests
      run: docker run non npm test
    - name: Run webpack
      run: docker run -v dist:/usr/src/app non npm run prod
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: us-east-1
    - name: Copy files to S3 with the AWS CLI
      run: |
        mkdir dist
        cd dist
        docker container create --name temp -v dist:/data non
        docker cp temp:/data/dist/* .
        docker cp temp:/data/public/* .
        aws s3 sync ./dist s3://nonograms
